### ISSUE TITLE
Rooted toon does not give results for boilerstatus

### ISSUE THREAD

**Issue by pdwonline** [cyberjunky/home-assistant-toon_boilerstatus#10]
I use a rooted toon and have a result on climate and sensors. For example:

http://192.168.0.14:10080/happ_thermstat?action=getThermostatInfo 
Returns a json like this: 

```
{"result":"ok", "currentTemp":"2204", "currentSetpoint":"1850", "currentInternalBoilerSetpoint":"6", "programState":"1", "activeState":"1", "nextProgram":"1", "nextState":"0", "nextTime":"1631293200","nextSetpoint":"2000","randomConfigId":"1804289383","errorFound":"255","connection":"0","burnerInfo":"0","otCommError":"0","currentModulationLevel":"0"}
```
The boilerstatus component gets a 404 resultcode on the defined url: http://192.168.0.14:10080/boilerstatus/boilervalues.txt

What am I doing wrong?

**Comment by cyberjunky** [comment]
You need to install toonstore and the boiler app, you also need a opentherm boiler.

**Comment by pdwonline** [comment]
Aha.. Thanx

**Comment by pdwonline** [comment]
Werkt inderdaad!
