### ISSUE TITLE
Cannot parse boiler status.txt

### ISSUE THREAD

**Issue by Tyrian81** [cyberjunky/home-assistant-toon_boilerstatus#16]
Just recently rooted my Toon and loving it !
Ggot the rooted thermostat into Home Assistant.
But the boiler status doesn't work 

```
Logger: custom_components.toon_boilerstatus.sensor
Source: custom_components/toon_boilerstatus/sensor.py:239
Integration: toon_boilerstatus ([documentation](https://github.com/cyberjunky/home-assistant-toon_boilerstatus), [issues](https://github.com/cyberjunky/home-assistant-toon_boilerstatus/issues))
First occurred: 21:46:40 (62 occurrences)
Last logged: 21:58:00

Cannot parse data received from Toon: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://192.168.188.34:80/boilerstatus/boilervalues.txt')
```
Running the latest HA in docker:
Home Assistant 2022.9.4
Frontend-versie: 20220907.2 - latest

**Comment by freakshock88** [comment]
Having a similair issue:

`Logger: custom_components.toon_boilerstatus.sensor
Source: custom_components/toon_boilerstatus/sensor.py:144
Integration: toon_boilerstatus ([documentation](https://github.com/cyberjunky/home-assistant-toon_boilerstatus), [issues](https://github.com/cyberjunky/home-assistant-toon_boilerstatus/issues))
First occurred: 12:14:28 PM (1 occurrences)
Last logged: 12:14:28 PM

Cannot poll Toon using url: http://192.168.1.196:10080/boilerstatus/boilervalues.txt`

**Comment by cyberjunky** [comment]
Hi @freakshock88 What do you get when you open the url in a webbrowser? You need to install the boilerstat app to have that data under that url.

**Comment by Tyrian81** [comment]
Yep solved, didn't have the boiler module installed thanks

**Comment by freakshock88** [comment]
@cyberjunky, I had the app installed on my Toon, just one minor version older. The strange thing is that the values were actually being updated in HA, even though I got this error in the log. I updated now to the latest version of the app on my Toon, and after restarting HA the error no longer shows up.
