### ISSUE TITLE
advice boilerintemp & boilerouttemp sensors unavailable information & documentation (see issue url below)

### ISSUE THREAD

**Issue by DoerakkerHA** [cyberjunky/home-assistant-toon_boilerstatus#18]
- boilerintemp &   - boilerouttemp are sensors created by the hacs toon boiler component. Given all the commotion with energy savings I wonder:
- were/are these sensors helpfull to identify potential savings issue?
- at one point these sensors stopped "working"; am i correct theses sensors likely still work but the data is not available to toon climate anymore?
- what route is advisable/possible to get to this data ? 
- should the documentation for this custom component be changed (I am willing to do so) as new users keep running into these "non working" sensors in home assistant

please advise

https://github.com/cyberjunky/home-assistant-toon_boilerstatus/issues/9#issuecomment-861373947

**Comment by cyberjunky** [comment]
What is the problem exactly?
First check if your Toon still has same/correct IP address as configured, then use a webbrowser to see if you get any values
```
http://<ip address>/boilerstatus/boilervalues.txt
```
If not check if you have the boiler app installed on the Toon.

**Comment by DoerakkerHA** [comment]
The device has a assigned static IPThe values are reported using a web browser The issue is: a lot of error messages in the HA log:This error originated from a custom integration.Logger: custom_components.toon_boilerstatus.sensorSource: custom_components/toon_boilerstatus/sensor.py:239 Integration: toon_boilerstatus (documentation, issues) First occurred: January 4, 2023 at 17:00:28 (89 occurrences) Last logged: 04:00:59Timeout error occurred while polling Toon using url: http://192.168.178.10:80/boilerstatus/boilervalues.txtCannot poll Toon using url: http://192.168.178.10:80/boilerstatus/boilervalues.txtThis error originated from a custom integration.Logger: custom_components.toon_climate.climateSource: custom_components/toon_climate/climate.py:240 Integration: toon_climate (documentation, issues) First occurred: January 4, 2023 at 17:01:28 (22 occurrences) Last logged: 01:57:28Timeout error occurred while polling Toon Thermostat using url: http://192.168.178.10:80/happ_thermstat?action=getThermostatInfoCannot poll Toon Thermostat using url: http://192.168.178.10:80/happ_thermstat?action=getThermostatInfoKind RegardsROnald GroeneveldSent from my iPhone +31 650 989 689Op 4 jan. 2023 om 13:39 heeft Ron ***@***.***> het volgende geschreven:﻿
What is the problem exactly?
First check if your Toon still has same/correct IP address as configured, then use a webbrowser to see if you get any values
http://<ip address>/boilerstatus/boilervalues.txt

If not check if you have the boiler app installed on the Toon.

**Comment by cyberjunky** [comment]
So if you click on these links from log (or copy paste) you get data?
If so your Toon is either unavailable at that time (does it ever show data) this can be cause by polling to often, some older Toon hang after a while and need a reboot (or you need to schedule a nightly reboot) or your Home Assistant instance cannot reach the Toon

**Comment by DoerakkerHA** [comment]
How can I schedule a reboot of toon? Kind RegardsROnald GroeneveldSent from my iPhone +31 650 989 689Op 5 jan. 2023 om 09:39 heeft Ron ***@***.***> het volgende geschreven:﻿
So if you click on these links from log (or copy paste) you get data?
If so your Toon is either unavailable at that time (does it ever show data) this can be cause by polling to often, some older Toon hang after a while and need a reboot (or you need to schedule a nightly reboot) or your Home Assistant instance cannot reach the Toon

**Comment by spreusterink** [comment]
Same issue. Boilerintemp en boilerouttemp have no data.
If i go to the url values.txt, in and out give a "null".
Toon has a static ip, boiler app is installed.
Data has been missing for 2 to 3 months now

**Comment by cyberjunky** [comment]
> Same issue. Boilerintemp en boilerouttemp have no data. If i go to the url values.txt, in and out give a "null". Toon has a static ip, boiler app is installed. Data has been missing for 2 to 3 months now

The boiler in and out temperature values where dropped long time ago, after a certain Toon firmware they were no longer available/read out by Toon. So nothing I can do about it.

**Comment by spreusterink** [comment]
Ah ok. Thnx for the reply!
