### ISSUE TITLE
Hot tap water sensor

### ISSUE THREAD

**Issue by parrel** [cyberjunky/home-assistant-toon_boilerstatus#19]
Hi,

I was thinking about rooting my Toon and was looking if I can still integrate it into HA. 

In the toon cloud integration, there is a Hot Tap Water sensor that I use to determine if the shower is on. Is there also such a sensor available in this integration?

Thanks in advance

**Comment by cyberjunky** [comment]
No unfortunately not, its limited to these values, where the boilerIn values are not reported anymore.
```
{"sampleTime":"04-01-2023 13:32:00","boilerSetpoint":34.89,"roomTempSetpoint":19.5,"boilerPressure":1.79,"roomTemp":19.65,"boilerOutTemp":null,"boilerInTemp":null,"boilerModulationLevel":0}
```

But!

If you also install my toon climate intergration you can get the valve setting with this template sensor:
```
- platform: template
    sensors:
      cv_driewegklep:
        unique_id: "driewegklep"
        friendly_name: "Driewegklep"
        value_template: >-
          {% if is_state_attr('climate.toon','burner_info', 0) %}
              Neutraal
          {% elif is_state_attr('climate.toon','burner_info', 1) %}
              CV
          {% elif is_state_attr('climate.toon','burner_info', 2) %}
              Warm Water
          {% endif %}
```
