### ISSUE TITLE
Set Pre heating warm water

### ISSUE THREAD

**Issue by Daandamhuis** [cyberjunky/home-assistant-toon_boilerstatus#2]
Hi,

So I was thinking, is it possible to set the Pre Heat water function from a rooted toon / Home Assistant.

I was thinking about setting this based on the time of day / week

![image](https://user-images.githubusercontent.com/3600611/76361442-5934f400-631f-11ea-9eb1-514c0f6a5e82.jpg)

**Comment by cyberjunky** [comment]
It doesn't seem possible to trigger this via the network, look here:
https://www.domoticaforum.eu/viewtopic.php?f=104&t=12813
