### ISSUE TITLE
toon_burnername

### ISSUE THREAD

**Issue by bvdf0251** [cyberjunky/home-assistant-toon_boilerstatus#22]
Hi Ron,

Coming from domoticz I had a Toon_burnername value. It shows off, ww(warm water) or CV.

I had a script running on that when burnername = cv then turn on floor heating.

Does this integration support the burnername?
As i dont see it in the values.

P.s. thanks for the toon_climate. New to HA but it took all of 2 minutes to set up and works perfectly.

**Comment by cyberjunky** [comment]
@bvdf0251 It's in the toon_climate intergration under atrributes. You can create a template sensor showing the name in a seperate sensor like so (from README of toon_climate) 
```template:
  - sensor:
    - name: "Toon Driewegklep"
      state: >-
          {% if is_state_attr('climate.toon','burner_info', 0) %}
             Neutraal
          {% elif is_state_attr('climate.toon','burner_info', 1) %}
             CV
          {% elif is_state_attr('climate.toon','burner_info', 2) %}
             Warm Water
          {% endif %}```

**Comment by bvdf0251** [comment]
That is awesome, thanks for the fast reply also.
