### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by Edwintenhaaf** [cyberjunky/home-assistant-toon_boilerstatus#3]
As requested by Homeassistant:

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for toon_boilerstatus doing I/O at custom_components/toon_boilerstatus/sensor.py, line 111: self._data = requests.get(self._build_url(), timeout=10, headers={'accept-encoding': None}).json()

**Comment by cyberjunky** [comment]
Thanks for reporting, this was fixed in latest version, can you update?
Release 1.0.4

**Comment by Edwintenhaaf** [comment]
I'm sorry. Did not use HACS (new to HA) but I do now. Updated and problem solved.
Thx for your effort!

**Comment by cyberjunky** [comment]
No problem, you get automatic notifications when new versions are released now.
