### ISSUE TITLE
2 toons

### ISSUE THREAD

**Issue by arcidodo** [cyberjunky/home-assistant-toon_boilerstatus#6]
I have 2 rooted toons. I can’t add them both to hassio climate is working because you can enter a name. But this is not possible for the boiler Status is it possible to add an name option so i can add both of them? 😁 

thx

**Comment by cyberjunky** [comment]
@arcidodo Can you try version 1.0.6? It will appear in HACS shortly, you can also download and install manually if you don't use HACS.

**Comment by harisosmancevic** [comment]
1.0.6 seems te break the whole integration for me..

**Comment by cyberjunky** [comment]
@harisosmancevic thanks for reporting, I made a boo boo and mixed up 2 integrations, please try 1.0.7.

**Comment by harisosmancevic** [comment]
1.0.7 works! Not sure if the issue with multiple Toon’s is working though, sorry for using this issue..

**Comment by arcidodo** [comment]
<img width="1509" alt="Schermafbeelding 2021-01-19 om 22 00 35" src="https://user-images.githubusercontent.com/678514/105092695-dd104e80-5aa1-11eb-9f00-065454193b2c.png">

get this error.

**Comment by svenahrensnl** [comment]
> 
> 
> 1.0.7 works! Not sure if the issue with multiple Toon’s is working though, sorry for using this issue.. seems that my room temp sensor is not working anymore, but not able to sort that out till tomorrow..
> 
> edit: when you do not use a name it seems to use the name of the integration:
> ![10B9862E-4D4B-4EE0-833B-6C3512F54ECB](https://user-images.githubusercontent.com/50442201/105091075-991c4a00-5a9f-11eb-8f00-b021ebffa132.jpeg)

Second that

![afbeelding](https://user-images.githubusercontent.com/34607207/105096449-5fe7d800-5aa7-11eb-828e-b4dd3ad0881b.png)

**Comment by arcidodo** [comment]
never mind! i got it working with 2 toons:-) thx i had to remove te config and restart home assistant. and then add the code back in the configuration.yaml. 

`  - platform: toon_boilerstatus
    host: 10.x.x.x
    port: 80
    scan_interval: 10
    resources:
      - boilersetpoint
      - boilerintemp
      - boilerouttemp
      - boilerpressure
      - boilermodulationlevel
      - roomtemp
      - roomtempsetpoint
      
  - platform: toon_boilerstatus
    name: toon_boilerstatus_brouwerij
    host: 10.x.x.x
    port: 80
    scan_interval: 10
    resources:
      - roomtemp`
