### ISSUE TITLE
Sensorname changed with last update (1.0.7)

### ISSUE THREAD

**Issue by svenahrensnl** [cyberjunky/home-assistant-toon_boilerstatus#7]
Instead of the normal sensor names the names are acumilated and pasted together:
![afbeelding](https://user-images.githubusercontent.com/34607207/105098414-4eec9600-5aaa-11eb-8569-95adda075014.png)

**Comment by cyberjunky** [comment]
@svenahrensnl Fixed with version 1.0.8 sorry for the troubles, thanks for reporting.
