### ISSUE TITLE
"boilerOutTemp":null,"boilerInTemp":null

### ISSUE THREAD

**Issue by hosmancevic** [cyberjunky/home-assistant-toon_boilerstatus#9]
Since a couple of days i am getting no value for boilerout and boilerin temp.
When i use this link: http://IPADDR/boilerstatus/boilervalues.txt
I am getting this response:
{"sampleTime":"01-04-2021 11:07:00","boilerSetpoint":6,"roomTempSetpoint":19.5,"boilerPressure":2,"roomTemp":20.41,"boilerOutTemp":null,"boilerInTemp":null,"boilerModulationLevel":0}

Also tried 1.05 and 1.08. now running on 1.09.

**Comment by cyberjunky** [comment]
@hosmancevic I have this as well, but the issue is with the boilervalue app on the Toon I think.

**Comment by gerritjonker** [comment]
Since firmware 5.39.7 boiler in/out temps are removed by Toon. And it seems they are not coming back. I removed these sensors.

**Comment by richardtrinks** [comment]
I have always had this option working. After the last update of the Toon, that no longer works.

Can a solution be realized for this? Thanks in advance.

**Comment by cyberjunky** [comment]
@richardtrinks It seems the Toon firmware doesn't fetch the values from OpenTherm bus anymore, so they are not available inside Toon so to speak.

**Comment by richardtrinks** [comment]
Thank you for your quick response. Could they be using other variables? Or that a downgrade of the Toon firmware is possible?

**Comment by cyberjunky** [comment]
Not that I know of, perhaps ask the forum on domoticaforum,eu
